title: Site de Ducks
author: A Duck
email: nonofyobusiness.com
description: > # this means to ignore newlines until "baseurl:"
  Ducks everywhere"
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
